feat: 유저 조회, 수정, 삭제 API개발
HBNU-SWUNIV/come-capstone23-f12 pull request #13
Opened 2023-04-13 08:19 UTC by tadaHP

# What is this PR?🔍

- Trello Card: https://trello.com/c/xdd17mfj
- Api: https://www.notion.so/jeidiiy/API-7c2a9051ecbc4f9e8e4d26b6d550a03f?pvs=4

## Changes📝

User 조회 수정 삭제 api를 개발했습니다.

- 회원id를 이용해 조회, 수정, 삭제 시행
- 수정 및 삭제시에 Session에 담겨있는 id값 확인

## Test Checklist✅

- [ ] 회원 조회, 수정, 삭제 레포지토리
    - [ ] 성공 케이스
    - [ ] 실패케이스
- [ ] 회원 조회, 수정, 삭제 서비스
    - [ ] 성공 케이스
    - [ ] 실패케이스
- [ ] 회원 조회, 수정, 삭제 컨트롤러
    - [ ] 성공 케이스
    - [ ] 실패케이스

2023-04-13 08:27 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java
> +		"select new io.f12.notionlinkedblog.domain.user.dto.info.UserSearchDto(u.id,"
select, from 같은 SQL 키워드는 대문자로 작성하는 편이 가독성이 더 좋아보입니다.

2023-04-13 08:29 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
> +	@DisplayName("유조 조회 리포지토리")
유조 -> 유저
오타 있습니다.

2023-04-13 08:33 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
> +			assertThat(findUserA).extracting("username").isEqualTo(user1.getUsername());
extractring으로 모든 필드를 꺼내서 비교하는 것보다 equals()와 hashCode()를 정의해서 비교하는 편이 좋아 보입니다.

2023-04-13 08:42 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
> +			@DisplayName("정보 가져오기")
DisplayName을 Test 위로 올려주세요! 보통 위에서 아래로 코드를 읽어내려가기 때문에 위쪽에 의미 파악을 할 수 있는 정보를 두는 게 좋습니다.

2023-04-13 08:44 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
> +			@DisplayName("유저 정보 변경 실패 - 해당 유저가 존재하지 않을때")
이 부분도 DisplayName을 위로 올려주쉐요

2023-04-13 08:56 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
> +				given(userDataRepository.findUserByDto(fakeIdForB))
이 테스트는 given만 작성되었고 when, then에 대한 부분은 없네요. 확인바랍니다.

2023-04-13 08:57 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
> +			@DisplayName("유저 정보 변경")
이 부분도 위로 올려주세요

2023-04-13 09:04 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java
> +		User findUser = userDataRepository.findById(id).orElse(null);
이 부분도 null로 처리하는 게 아니라 예외를 던지는 방식으로 하는 게 좋아 보입니다.

2023-04-13 09:08 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
> +	void specificUserDTOCheck() {
메서드는 동사로 시작하는 편이 가독성이 좋습니다. 이 경우 checkSpecificUserDto가 좋겠네요.

2023-04-13 09:12 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
> +@TestMethodOrder(value = MethodOrderer.OrderAnnotation.class)
순서가 왜 문제가 된건지 커밋 내역에 적어줬으면 좋았을 것 같습니다. 코멘트로 순서가 왜 문제가 되었는지 알려주시면 좋겠습니다.

2023-04-13 09:23 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
> +		return "done";
REST API를 제공해야 하는데 String으로 done을 프론트에 던져주면 안 됩니다. 의미 있는 상태코드와 함께 JSON 형식에 맞는 응답 객체를 반환해줘야 합니다. DELETE의 경우 따로 응답 값으로 내려줄 게 없으므로 응답 상태 코드를 204(No Content)로 내려주는 게 바람직해보입니다. 이 부분은 REST API를 공부해보세요.

2023-04-13 09:24 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
> +		return sessionId;
이 경우도 sessionId를 내려주는 게 아니라 OK와 같은 의미 있는 응답 코드로 ResponseEntity에 담아서 내려줘야 합니다.

2023-04-13 09:27 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
> +		ResultActions resultActions = mockMvc.perform(get("/api/users/1"))
given, when, then을 주석으로 명시해서 코드를 보는 입장에서 명확하게 해주세요. 다른 테스트도 모두 마찬가지입니다.

2023-04-13 09:29 UTC, jeidiiy reviewed
코멘트 확인바랍니다.

2023-04-13 09:31 UTC, jeidiiy requested changes
코멘트 확인바랍니다.

2023-04-13 16:39 UTC, tadaHP commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
> +@TestMethodOrder(value = MethodOrderer.OrderAnnotation.class)
`@Order`를 사용한 이유는 테스트는 순서를 보장해주지 않고 실행하게 되는데 **정상 조회 테스트**시 userId를 1, 2번으로 고정하고 사용을 했습니다. 이 때 **비정상 조회 테스트**가 먼저 실행이 되면 **정상 조회 테스트**시 userId가 1, 2번이 아닌 2, 3번으로 할당되어 오류가 발생합니다.
현재는 `@AfterEach`를 사용하여 **모든 데이터를 삭제 후 다시 테스트를 진행**하게 코드를 수정했습니다

2023-04-13 17:28 UTC, KyleRuiz approved these changes

2023-04-14 02:08 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserSearchDto.java
> +	public int hashCode() {
이 클래스 컴파일했을 때 생성되는 클래스 파일에서 equals()와 hashCode()가 어떻게 만들어졌는지 알 수 있을까요? Data 어노테이션이 적용되어 있는데 hashCode()를 직접 오버라이드하면 어떤 게 적용되는지 궁금합니다.

2023-04-14 02:09 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
>  		@Order(1)
순서가 왜 문제가 되는지 말해주시면 좋겠습니다.

2023-04-14 02:13 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java
> +	public void deleteUserInfo(@PathVariable Long id, HttpSession session) {
Clean Code 규칙 중 '의미 있는 이름'에 의하면 Info와 같은 접미사는 지양하는 편이 좋습니다. 보다 직관적으로 클래스가 어떤 역할을 하는지 알 수 있는 이름이 좋습니다. 이 메서드 이름으로 봐서는 유저의 어떤 정보를 지우는지 알 수 없습니다.

2023-04-14 02:15 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
> +	class checkUserInfoApiTest {
클래스 이름은 명사, 명사구의 영문 대문자로 시작해야 합니다. 이런 경우 UserApiCheckingTest 와 같은 방식이 알맞을 것 같습니다.

2023-04-14 02:16 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
> +	class editUserInfoApiTest {
이 부분도 영문 대문자의 명사 형태로 시작하도록 변경해주세요.

2023-04-14 02:17 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
>  					status().is3xxRedirection(),
3xx이 아니라 정확히 어떤 응답 코드가 내려가는지 명시해주세요

2023-04-14 02:18 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
>  					status().is4xxClientError()
이 부분도 4xx이 아니라 400번대의 어떤 응답 코드가 내려가는지 명시해주세요.

2023-04-14 02:18 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
>  					status().is4xxClientError()
위 코멘트와 마찬가지입니다.

2023-04-14 02:18 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
>  					status().is4xxClientError()
앞선 코멘트와 같습니다.

2023-04-14 02:19 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
>  					status().is4xxClientError()
앞선 코멘트와 같습니다.

2023-04-14 02:20 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
> +		class EditUserTest {
동사가 아니라 명사 형태로 시작하도록 변경해주세요.

2023-04-14 02:20 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
>  				@DisplayName("해당 유저가 존재하지 않을때")
DisplayName을 Test위로 올려주세요.

2023-04-14 02:21 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
> +		class DeleteUserTest {
명사 형태로 변경해주세요.

2023-04-14 02:30 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
> +@TestMethodOrder(value = MethodOrderer.OrderAnnotation.class)
데이터를 삭제해도 DB의 AUTO INCREMENT 값은 이미 증가한 상태로 있기 때문에 같은 오류가 발생할 겁니다. 이런 경우 `@BeforeEach`에서 AUTO INCREMENT를 초기화하는 NATIVE SQL을 직접 작성하는 게 좋아 보입니다.

2023-04-14 02:35 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java
> +			long id = 5L;
id를 바꾸는 방법은 근본적인 해결책이 아닙니다. `Order()` 또한 정말 피치 못할 경우에만 사용해야 합니다. 이런 경우에는 `Order()`를 적용하지 않아도 가능할 것으로 보입니다.

2023-04-14 10:55 UTC, jeidiiy commented on 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java
> +)
이 부분은 나중에 성능에 관련해서 최적화가 필요할 수도 있겠군요.

2023-04-14 11:01 UTC, jeidiiy approved these changes
고생하셨습니다. 처음보다 코드가 훨씬 가독성 있게 바뀌었네요.
프로그램은 주석보다 코드만으로 읽히는 게 가장 좋다고 합니다. 이 부분 항상 고려해주면 좋을거라 생각되며 CODE 시리즈 중 Clean Code라는 책을 추천드립니다. 정독하면 좋겠지만 필요한 챕터만 부분적으로 봐도 참 좋은 책입니다.

2023-04-14 12:40 UTC, KyleRuiz approved these changes

2023-04-15 07:57 UTC, merged